import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ChatPanel from '../ChatPanel';

// Mock analytics to prevent side effects
vi.mock('../../analytics', () => ({
  logEvent: vi.fn(),
}));

// Mock fetch globally
const mockFetch = vi.fn();
global.fetch = mockFetch;

describe('ChatPanel', () => {
  beforeEach(() => {
    mockFetch.mockReset();
    // Default mock for any auto-triggered fetches
    mockFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({
        response: 'Test response.\n\n[BADGE: Beginner Friendly]',
        intent: 'general',
        powered_by: 'Google Gemini',
      }),
    });
  });

  it('renders the chat heading', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByText('AI Advisory')).toBeInTheDocument();
  });

  it('renders the Gemini attribution label', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByLabelText('Generated by Google Gemini')).toBeInTheDocument();
  });

  it('renders empty state with context-aware message for registered users', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByText(/you're registered/i)).toBeInTheDocument();
  });

  it('renders empty state for ready-to-vote users', () => {
    render(<ChatPanel journey="Ready to Vote" />);
    expect(screen.getByText(/ready to vote/i)).toBeInTheDocument();
  });

  it('renders the chat input form', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByLabelText('Type your question here')).toBeInTheDocument();
  });

  it('disables send button when input is empty', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByLabelText('Send question to ELARA')).toBeDisabled();
  });

  it('enables send button when input has text', async () => {
    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" />);
    await user.type(screen.getByLabelText('Type your question here'), 'How to vote?');
    expect(screen.getByLabelText('Send question to ELARA')).toBeEnabled();
  });

  it('sends message and displays AI response', async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: () => Promise.resolve({
        response: 'You need to register first.\n\n[BADGE: Beginner Friendly]',
        intent: 'general',
        powered_by: 'Google Gemini',
      }),
    });

    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" externalQuery={null} />);

    await user.type(screen.getByLabelText('Type your question here'), 'How to vote?');
    await user.click(screen.getByLabelText('Send question to ELARA'));

    await waitFor(() => {
      expect(screen.getByText(/register first/i)).toBeInTheDocument();
    });
  });

  it('displays trust badges from AI response', async () => {
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: () => Promise.resolve({
        response: 'Steps here.\n\n[BADGE: Step-by-Step Guidance]',
        intent: 'journey',
        powered_by: 'Google Gemini',
      }),
    });

    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" externalQuery={null} />);

    await user.type(screen.getByLabelText('Type your question here'), 'Next steps');
    await user.click(screen.getByLabelText('Send question to ELARA'));

    await waitFor(() => {
      expect(screen.getByText('Step-by-Step Guidance')).toBeInTheDocument();
    });
  });

  it('shows error message when fetch fails after retries', async () => {
    mockFetch.mockRejectedValue(new Error('Network error'));

    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" externalQuery={null} />);

    await user.type(screen.getByLabelText('Type your question here'), 'Hello');
    await user.click(screen.getByLabelText('Send question to ELARA'));

    await waitFor(() => {
      expect(screen.getByText(/service unavailable/i)).toBeInTheDocument();
    }, { timeout: 10000 });
  });

  it('renders walkthrough button in empty state', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByLabelText(/start guided walkthrough/i)).toBeInTheDocument();
  });

  it('displays journey guidance showing current and next step', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByText('Verification')).toBeInTheDocument();
    expect(screen.getByText('Polling Day')).toBeInTheDocument();
  });

  it('has accessible chat form with proper aria label', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByRole('form', { name: 'Ask ELARA a question' })).toBeInTheDocument();
  });

  it('has accessible chat log region', () => {
    render(<ChatPanel journey="Registered" />);
    expect(screen.getByRole('log')).toBeInTheDocument();
  });

  it('sets aria-busy on chat messages during loading', async () => {
    mockFetch.mockImplementation(() => new Promise(() => {})); // never resolves

    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" externalQuery={null} />);

    await user.type(screen.getByLabelText('Type your question here'), 'Test');
    await user.click(screen.getByLabelText('Send question to ELARA'));

    const log = screen.getByRole('log');
    expect(log).toHaveAttribute('aria-busy', 'true');
  });

  it('passes lang parameter in API request', async () => {
    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" externalQuery={null} lang="hi" />);

    await user.type(screen.getByLabelText('Type your question here'), 'मतदान कैसे करें?');
    await user.click(screen.getByLabelText('Send question to ELARA'));

    await waitFor(() => {
      const call = mockFetch.mock.calls.find(c => {
        const body = JSON.parse(c[1].body);
        return body.lang === 'hi';
      });
      expect(call).toBeTruthy();
    });
  });

  it('renders disclaimer with official ECI link', () => {
    render(<ChatPanel journey="Registered" />);
    const link = screen.getByText('eci.gov.in');
    expect(link).toHaveAttribute('href', 'https://eci.gov.in');
    expect(link).toHaveAttribute('rel', 'noopener noreferrer');
  });

  it('clears input after sending a message', async () => {
    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" externalQuery={null} />);

    const input = screen.getByLabelText('Type your question here');
    await user.type(input, 'How to vote?');
    await user.click(screen.getByLabelText('Send question to ELARA'));

    expect(input).toHaveValue('');
  });

  it('renders user message with correct label', async () => {
    const user = userEvent.setup();
    render(<ChatPanel journey="Registered" externalQuery={null} />);

    await user.type(screen.getByLabelText('Type your question here'), 'Test question');
    await user.click(screen.getByLabelText('Send question to ELARA'));

    expect(screen.getByText(/You/i)).toBeInTheDocument();
  });
});
