import { useState, useEffect, useRef, useCallback } from 'react';

/** Generate unique message IDs to avoid array-index keys */
let messageIdCounter = 0;
function createMessage(role, text) {
  return { id: ++messageIdCounter, role, text };
}

export default function ChatPanel({ journey, externalQuery }) {
  const [query, setQuery] = useState('');
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef(null);
  const prevExternalQuery = useRef('');
  const hasAutoTriggered = useRef(false);
  const lastTopicRef = useRef(null);

  /** Derive topic from query for micro-memory */
  function detectTopic(text) {
    const t = text.toLowerCase();
    if (t.includes('register') || t.includes('registration')) return 'registration';
    if (t.includes('verif')) return 'verification';
    if (t.includes('poll') || t.includes('vote') || t.includes('election day')) return 'polling';
    if (t.includes('count') || t.includes('result')) return 'counting';
    if (t.includes('document') || t.includes('aadhaar') || t.includes('id proof')) return 'documents';
    if (t.includes('deadline') || t.includes('date') || t.includes('when')) return 'deadlines';
    return null;
  }

  /** Journey step progression map */
  const STEP_MAP = {
    'Not Registered': { current: 'Registration', next: 'Verification' },
    'Registered': { current: 'Verification', next: 'Polling Day' },
    'Ready to Vote': { current: 'Polling Day', next: 'Results' },
  };

  /** Send a message to the ELARA API */
  const sendMessage = useCallback(async (messageText) => {
    const q = messageText.trim();
    if (!q || loading) return;

    setMessages((prev) => [...prev, createMessage('user', q)]);
    setQuery('');
    setLoading(true);

    try {
      const res = await fetch('/api/ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: q, context: journey, lastTopic: lastTopicRef.current }),
      });
      lastTopicRef.current = detectTopic(q);
      const data = await res.json();
      setMessages((prev) => [
        ...prev,
        createMessage('ai', data.response || data.error),
      ]);
    } catch {
      setMessages((prev) => [
        ...prev,
        createMessage('ai', 'Service unavailable. Please try again.'),
      ]);
    } finally {
      setLoading(false);
    }
  }, [journey, loading]);

  // Smart Guidance: auto-trigger on first load when "Not Registered"
  useEffect(() => {
    if (journey === 'Not Registered' && !hasAutoTriggered.current && messages.length === 0) {
      hasAutoTriggered.current = true;
      sendMessage(
        "I'm not registered to vote yet. Since that's my current stage, guide me through exactly what I should do next — documents needed, where to apply, and any deadlines I should know about."
      );
    }
  }, [journey, messages.length, sendMessage]);

  // Handle external queries from Timeline clicks
  useEffect(() => {
    if (externalQuery && externalQuery !== prevExternalQuery.current) {
      prevExternalQuery.current = externalQuery;
      sendMessage(externalQuery);
    }
  }, [externalQuery, sendMessage]);

  // Auto-scroll to latest message
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const handleSubmit = (e) => {
    e.preventDefault();
    sendMessage(query);
  };

  return (
    <section className="card chat-panel" aria-labelledby="chat-heading">
      <div className="chat-header">
        <h2 id="chat-heading">
          <span className="section-icon" aria-hidden="true">💬</span>
          AI Advisory
          <span className="chat-header-sub">— Personalized for your journey</span>
        </h2>
        <span className="gemini-label" aria-label="Generated by Google Gemini">
          <span className="gemini-dot" aria-hidden="true"></span>
          Generated by Gemini
        </span>
      </div>
      <div className="chat-guidance" aria-live="polite">
        <span className="guidance-icon" aria-hidden="true">✨</span>
        {STEP_MAP[journey]
          ? <>
              Currently at: <strong>{STEP_MAP[journey].current}</strong>
              <span className="step-progress-arrow" aria-hidden="true"> → </span>
              Next: <strong>{STEP_MAP[journey].next}</strong>
            </>
          : "I'll guide you step-by-step based on where you are in the voting process."
        }
      </div>

      <div className="chat-messages" role="log" aria-live="polite" aria-label="Chat messages">
        {messages.length === 0 && !loading && (
          <div className="chat-empty">
            <div className="chat-empty-icon" aria-hidden="true">🗳️</div>
            <p className="chat-placeholder">
              {journey === 'Not Registered'
                ? "Since you're not registered yet, let me help you get started."
                : journey === 'Registered'
                  ? "You're registered — let's make sure you're fully prepared."
                  : "You're ready to vote! Ask me anything about election day."}
            </p>
            <p className="chat-hint">Click a timeline step or type a question — I'll guide you through it.</p>
          </div>
        )}
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`message ${msg.role}`}
            aria-label={`${msg.role === 'ai' ? 'ELARA' : 'You'}: ${msg.text.substring(0, 100)}`}
          >
            <span className="message-label">
              {msg.role === 'ai' ? '🤖 ELARA' : '👤 You'}
            </span>
            <p className="message-text">{msg.text}</p>
          </div>
        ))}
        {loading && (
          <div className="message ai loading-message" aria-live="assertive" aria-label="ELARA is thinking">
            <span className="message-label">🤖 ELARA</span>
            <div className="typing-indicator">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      <form className="chat-form" onSubmit={handleSubmit} aria-label="Ask ELARA a question">
        <label htmlFor="chat-input" className="sr-only">
          Your question
        </label>
        <input
          id="chat-input"
          className="chat-input"
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Ask about voting, registration, timelines…"
          aria-label="Type your question here"
          maxLength={1000}
          disabled={loading}
        />
        <button
          type="submit"
          className="send-btn"
          aria-label="Send question to ELARA"
          disabled={loading || !query.trim()}
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
            <path d="M22 2L11 13M22 2L15 22L11 13M22 2L2 9L11 13" />
          </svg>
          Ask
        </button>
      </form>
    </section>
  );
}
